ndn_cli :
	g++ -g ndn_client.cpp rqueue.cpp -o osn_client -std=c++14 -lndn-cxx -lboost_system -lpthread -ljsoncpp

regmain :
	g++ -o regmain addTrustNode.cpp -std=c++14 -lndn-cxx -lboost_system -lpthread
